[package]
name = "youtube_to_mp3"
version = "0.1.0"
edition = "2021"

[dependencies]
google-youtube3 = "2.0"
tokio = { version = "1", features = ["full"] }
youtube-dl-rs = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
