CREATE DATABASE rust_sample;
CREATE TABLE product_category (
	id INTEGER PRIMARY KEY,
	name VARCHAR ( 250 ) UNIQUE NOT NULL
);

CREATE TABLE product (
	id INTEGER PRIMARY KEY,
	name VARCHAR ( 250 ) UNIQUE NOT NULL,
    price INTEGER NOT NULL,
    category_id INTEGER
);