extend = "../../Makefile.toml"

[tasks.examples_build]
alias = "build"

[tasks.examples_build_release]
alias = "build_release"

[tasks.examples_run]
alias = "run"

[tasks.examples_test]
alias = "test"

[tasks.examples_run_release]
alias = "run_release"